name: gateway
repo: https://github.com/254carbon/254carbon-access
path: service_gateway
domain: access
version: 0.1.0
maturity: stable
runtime: python
api_contracts:
- gateway-core@1.0.0
events_in:
- pricing.curve.updates.v1
events_out:
- metrics.request.count.v1
dependencies:
  internal:
  - auth
  - entitlements
  - metrics
  - projection
  external:
  - clickhouse
  - redis
quality:
  coverage: 0.88
  lint_pass: true
  open_critical_vulns: 0
security:
  signed_images: true
  policy_pass: true
last_update: '2025-10-08T04:49:24.866038+00:00'
