name: indexer-worker
repo: https://github.com/254carbon/254carbon-ml
path: service-indexer-worker
domain: ml
version: 0.1.0
maturity: beta
runtime: python
api_contracts: []
events_in:
- ml.embedding.reindex.request.v1
events_out:
- ml.embedding.generated.v1
dependencies:
  internal:
  - vector-store-adapter
  external:
  - embedding-service
  - postgres
  - redis
quality:
  coverage: 0.59
  lint_pass: false
  open_critical_vulns: 0
security:
  signed_images: false
  policy_pass: false
last_update: '2025-10-07T19:48:13.018538+00:00'
