name: mlflow-server
repo: https://github.com/254carbon/254carbon-ml
path: service-mlflow
domain: ml
version: 0.1.0
maturity: beta
runtime: python
api_contracts:
- mlflow-api@2.8.1
events_in: []
events_out:
- ml.model.promoted.v1
dependencies:
  internal: []
  external:
  - minio
  - postgres
  - redis
quality:
  coverage: 0.55
  lint_pass: true
  open_critical_vulns: 1
security:
  signed_images: false
  policy_pass: false
last_update: '2025-10-07T19:48:13.018538+00:00'
